<?php

namespace AppBundle\Repository;

/**
 * LocationDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLocationIdComputed($id) {

        $sql = "
        SELECT 
          location_id,
          `date`,
          ROUND(temperature) as temp_c,
          ROUND(temperature * 1.8 + 32) as temp_f
          FROM 
            location_data 
          WHERE
           location_id = :id
         ";

        $statement = $this->getEntityManager()->getConnection()->prepare($sql);
        $statement->bindValue('id', $id);
        $statement->execute();

        return $statement->fetchAll();
    }
}
